#!/usr/bin/env python3
"""Build a ThingsBoard dashboard and widget from an exported line-chart widget.

Takes the widget as exported from ThingsBoard and produces:

  * output_dashboard.json  - importable via Dashboards -> "+" -> Import dashboard
  * output_widget.json       - the widget on its own, for dropping into an
                               existing dashboard via Import widget

What it changes relative to the source export:

  1. Splits multiple series onto their own labelled y-axes. They may carry
     different units on wildly different scales, so a single shared axis
     cannot be given a meaningful label.
  2. Labels the x-axis and turns the legend on (multiple axes are unreadable
     without it).
  3. Wires the two download scripts in actions/ onto the widget header.

Re-run after editing anything in actions/:

    python3 build_dashboard.py
"""

import argparse
import json
import os
import uuid
from pathlib import Path
from typing import Any

from dashboard_config import AXIS_PLAN, HEADER_BUTTONS, X_AXIS_LABEL, WIDGET_SIZE

HERE = Path(__file__).parent
ACTIONS = HERE / "actions"


def stable_id(device_id: str, name: str) -> uuid.UUID:
    """Generate a stable UUID for a given device_id and name.

    Provides a deterministic UUID, so rebuilding the dashboard produces a clean
    diff instead of churning every UUID. Re-importing then updates the same
    dashboard rather than making a duplicate.
    
    Args:
        device_id: The device ID to use as the namespace for the UUID.
        name: The name to use as the name for the UUID.
    
    Returns:
        A stable UUID generated from the device_id and name.
    """
    return str(uuid.uuid5(uuid.UUID(device_id), name))


def scaling_preamble(axis_plan: dict[str, dict[str, Any]] = AXIS_PLAN) -> str:
    """Emit the divisors and number of decimal places to convert raw telemetry.

    The ThingsBoard chart displays processed telemetry data but the ThingsBoard
    API returns the raw data. This preamble lets the download scripts scale the
    raw telemetry to match the chart, using the same number of decimal places.

    Args:
        axis_plan: The axis plan to use for generating the divisors and decimals,
            which must contain the keys "key", "divisor", and "decimals" for each
            axis.

    Returns:
        A string containing the JavaScript code for the divisors and decimals.
    """
    divisor_mapping = {key: plan["divisor"] for key, plan in axis_plan.items()}
    decimals_mapping = {key: plan["decimals"] for key, plan in axis_plan.items()}
    return (
        "// Generated by build_dashboard.py from AXIS_PLAN - do not edit here.\n"
        "// Divisors to convert the raw telemetry and match the chart. The same\n"
        "// number of decimal places are also applied.\n"
        f"var DIVISORS = {json.dumps(divisor_mapping, ensure_ascii=False)};\n"
        f"var DECIMALS = {json.dumps(decimals_mapping, ensure_ascii=False)};\n"
    )


def load_action(filename: str) -> str:
    """Concatenate the shared helpers with an action script.

    ThingsBoard evaluates each custom action as one self-contained function
    body, so the helpers have to be inlined rather than imported.

    Args:
        filename: The name of the action script file to load.
    
    Returns:
        A string containing the concatenated JavaScript code of the helpers
            and the action script.
    """
    common = (ACTIONS / "_common.js").read_text()
    body = (ACTIONS / filename).read_text()
    return f"{scaling_preamble()}\n{common}\n{body}"


def apply_axes(config: dict, axis_plan: dict[str, dict[str, Any]] = AXIS_PLAN) -> None:
    """Apply the axis plan to the widget configuration.
    
    Args:
        config: The widget configuration dictionary to modify.
        axis_plan: The axis plan to use for configuring the axes, which must
            contain the keys 'key', 'axis', 'label', 'position', 'units',
            'raw_units', 'divisor', 'decimals', 'min' and 'max' for each axis.
    """
    settings = config["settings"]
    template = settings["yAxes"]["default"]

    keys_by_name = {}
    for datasource in config["datasources"]:
        for key in datasource["dataKeys"]:
            keys_by_name[key["name"]] = key

    y_axes = {}
    # Iterate through the keys in the source widget
    for key_name, key in keys_by_name.items():
        # Check that an axis plan has been provided for the key
        if key_name not in axis_plan:
            raise SystemExit(f"no axis plan provided for data key {key_name!r}")
        plan = axis_plan[key_name]

        colour = key["color"]

        axis = json.loads(json.dumps(template))  # deep copy
        axis.update(
            {
                "id": plan["axis"],
                "order": plan["order"],
                "label": plan["label"],
                "position": plan["position"],
                "units": plan["units"],
                "decimals": plan["decimals"],
                "show": True,
                # Colour the axis to match its series, so three axes stay
                # readable without tracing lines back to the legend.
                "labelColor": colour,
                "tickLabelColor": colour,
                "ticksColor": colour,
                "lineColor": colour,
                # Only the leftmost axis draws gridlines; three overlapping sets
                # of split lines is visual noise.
                "showSplitLines": plan["position"] == "left",
                # null lets ECharts autoscale that end of the axis.
                "min": plan["min"],
                "max": plan["max"],
            }
        )
        y_axes[plan["axis"]] = axis

        key["settings"]["yAxisId"] = plan["axis"]
        key["units"] = plan["units"]
        key["decimals"] = plan["decimals"]

        # Chart-side scaling
        if plan["divisor"] != 1:
            key["usePostProcessing"] = True
            key["postFuncBody"] = f"return value / {plan['divisor']};"
        else:
            key["usePostProcessing"] = False
            key["postFuncBody"] = ""

    settings["yAxes"] = y_axes

    # yAxis is the legacy single-axis block; keep it consistent with the
    # left-hand axis so older renderers do not fall back to an empty label.
    settings["yAxis"]["label"] = y_axes["default"]["label"]

    settings["xAxis"]["label"] = X_AXIS_LABEL

    # Three axes are unreadable without a legend to map colour -> series.
    settings["showLegend"] = True

    # Series carry different units, so an aggregate column in the legend is
    # meaningless across them. Name only.
    settings["legendConfig"].update(
        {
            "showAvg": False,
            "showMin": False,
            "showMax": False,
            "showTotal": False,
            "showLatest": False,
        }
    )


def apply_actions(
        config: dict, header_buttons: list[dict[str, str]] = HEADER_BUTTONS
    ) -> None:
    """Apply the actions to the header buttons for the widget.
    
    Args:
        config: The widget configuration dictionary to modify.
        header_buttons: A list of dictionaries containing the button configuration,
            each with keys 'name', 'icon', and 'script'.
    """
    # Used for generating UUIDs
    device_id = config["datasources"][0]["deviceId"]

    buttons = []
    for button in header_buttons:
        buttons.append(
            {
                "id": stable_id(device_id, button["script"]),
                "name": button["name"],
                "icon": button["icon"],
                "type": "custom",
                "customFunction": load_action(button["script"]),
                "useShowWidgetActionFunction": False,
                "showWidgetActionFunction": "return true;",
            }
        )
    config["actions"] = {"headerButton": buttons}


def size_widget(
        widget: dict[str, Any], size_x: float = WIDGET_SIZE["x"], size_y: float = WIDGET_SIZE["y"]
    ) -> None:
    """Set the size and position of the widget in the dashboard grid.

    Args:
        widget: The widget dictionary to modify.
        size_x: The width of the widget in grid units.
        size_y: The height of the widget in grid units.
    """
    widget["sizeX"] = size_x
    widget["sizeY"] = size_y
    widget["row"] = 0
    widget["col"] = 0


def build_widget_export(
        widget: dict[str, Any], size_x: float = WIDGET_SIZE["x"], size_y: float = WIDGET_SIZE["y"]
    ) -> dict[str, Any]:
    """Build a widget-only export, same shape ThingsBoard produces for 'Export widget'.
    
    Args:
        widget: The widget dictionary to include in the export.
        size_x: The width of the widget in grid units.
        size_y: The height of the widget in grid units.
    
    Returns:
        A dictionary representing the widget export.
    """
    # Widget-only export, same shape ThingsBoard produces for "Export widget".
    widget_export = {
        "widget": widget,
        "aliasesInfo": {"datasourceAliases": {}, "targetDeviceAlias": None},
        "filtersInfo": {"datasourceFilters": {}},
        "originalSize": {"sizeX": size_x, "sizeY": size_y},
        "originalColumns": 24,
    }
    return widget_export


def get_widget_id(config: dict[str, Any]) -> str:
    """Generate a stable UUID for the widget using the device ID."""
    device_id = config["datasources"][0]["deviceId"]
    widget_id = stable_id(device_id, f"widget:{config['title'] or 'device'}-line-chart")
    return widget_id


def build_dashboard_export(
        config: dict[str, Any],
        widget: dict[str, Any],
        title: str,
        size_x: float = WIDGET_SIZE["x"],
        size_y: float = WIDGET_SIZE["y"],
    ) -> dict[str, Any]:
    """Build a dashboard export.

    Args:
        config: The dashboard configuration dictionary.
        widget: The widget dictionary to include in the dashboard.
        title: The title of the dashboard.
        size_x: The width of the widget in grid units.
        size_y: The height of the widget in grid units.

    Returns:
        A dictionary representing the dashboard export.
    """
    widget_id = get_widget_id(config)

    dashboard = {
        "title": title,
        "name": title,
        "image": None,
        "mobileHide": False,
        "mobileOrder": None,
        "configuration": {
            "description": f"{title} telemetry with CSV export buttons in the widget header.",
            "widgets": {widget_id: widget},
            "states": {
                "default": {
                    "name": title,
                    "root": True,
                    "layouts": {
                        "main": {
                            "widgets": {
                                widget_id: {
                                    "sizeX": size_x,
                                    "sizeY": size_y,
                                    "row": 0,
                                    "col": 0,
                                }
                            },
                            "gridSettings": {
                                "backgroundColor": "#eeeeee",
                                "columns": 24,
                                "margin": 10,
                                "backgroundSizeMode": "100%",
                            },
                        }
                    },
                }
            },
            "entityAliases": {},
            "filters": {},
            # Inherited by the widget, which has useDashboardTimewindow: true.
            "timewindow": config["timewindow"],
            "settings": {
                "stateControllerId": "entity",
                "showTitle": True,
                "showDashboardsSelect": True,
                "showEntitiesSelect": True,
                "showDashboardTimewindow": True,
                "showDashboardExport": True,
                "toolbarAlwaysOpen": True,
            },
        },
    }
    return dashboard


def write_json(export: dict[str, Any], filename: Path) -> None:
    """Write a JSON export to file.

    Args:
        export: The dictionary to write as JSON.
        filename: The path to the file where the JSON should be written.
    """
    filename.write_text(json.dumps(export, indent=2, ensure_ascii=False) + "\n")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.
    
    Reads the exported widget JSON and dashboard title from the command line.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=HERE / "source" / "line_chart_rl000590.json",
        help="exported widget JSON to build from (default: %(default)s)",
    )
    parser.add_argument(
        "--title",
        default="RL000590",
        help="title to use for dashboard export (default: %(default)s)",
    )
    parser.add_argument(
        "--output-dir",
        default=HERE / "output",
        help="directory to write output JSON files (default: %(default)s)",
        type=Path,
    )
    return parser.parse_args()


def main(axis_plan: dict[str, dict[str, Any]] = AXIS_PLAN) -> None:
    """Build a ThingsBoard dashboard and widget from an exported line-chart widget."""
    args = parse_args()
    export = json.loads(args.source.read_text())
    widget = export["widget"]
    config = widget["config"]
    widget_name = config["title"]

    # Create output directory to save json files
    os.makedirs(args.output_dir, exist_ok=True)

    # Apply axes and actions to the widget configuration
    apply_axes(config)
    apply_actions(config)

    # Create the widget-only export and write to file
    size_widget(widget)
    widget_export = build_widget_export(widget)
    write_json(widget_export, args.output_dir / f"{widget_name}_widget.json")

    # Create the dashboard export and write to file
    dashboard = build_dashboard_export(config, widget, args.title)
    write_json(dashboard, args.output_dir / f"{widget_name}_dashboard.json")

    # Print summary
    print(
        f"wrote {args.output_dir / f'{widget_name}_dashboard.json'} and "
        f"{args.output_dir / f'{widget_name}_widget.json'}"
    )
    for axis_id, axis in config["settings"]["yAxes"].items():
        plan = next(axis_plan[key] for key in axis_plan if axis_plan[key]["axis"] == axis_id)
        scale = "raw" if plan["divisor"] == 1 else f"/{plan['divisor']}"
        if plan["min"] is None and plan["max"] is None:
            rng = "auto"
        else:
            rng = f"{plan['min']}..{plan['max']}"
        print(
            f"  y-axis {axis_id:12s} {axis['position']:5s} {axis['label']:20s}"
            f" {axis['labelColor']}  {scale}, {axis['decimals']}dp, range {rng}"
        )
    print(f"  x-axis {'':12s} {'bottom':5s} {config['settings']['xAxis']['label']}")
    print(f"  legend aggregates: {'off' if not config['settings']['legendConfig']['showAvg'] else 'ON'}")
    for button in config["actions"]["headerButton"]:
        print(f"  header button: {button['name']} ({len(button['customFunction'])} chars)")


if __name__ == "__main__":
    main()
